### ISSUE TITLE
Unable to run the game due to missing resource

### ISSUE THREAD

**Issue by dev-vaayen** [DTLP/mini_tanks#1]
Hi @DTLP,

I have followed the following steps for the game's installation:
```
git clone https://github.com/DTLP/mini_tanks.git
cd mini_tanks
go run ./cmd/mini_tanks.go
```

The error that I am displayed with after running the code is:
> go run ./cmd/mini_tanks.go
> panic: open resources/green_tank_turret.png: no such file or directory
> 
> goroutine 1 [running, locked to thread]:
> github.com/DTLP/mini_tanks/internal/scene.loadImages()
> 	/home/user/mini_tanks/internal/scene/actors.go:295 +0x105
> github.com/DTLP/mini_tanks/internal/scene.init.0()
> 	/home/user/mini_tanks/internal/scene/actors.go:283 +0x17
> exit status 2

I am still so excited to play the game, please help me resolve this issue! :)

**Comment by DTLP** [comment]
Hi @Shayah-01,
Apologies for the late response.
Are you sure you are executing `go run ./cmd/mini_tanks.go` from the root repo directory `mini_tanks` and not from the `cmd` directory?
I have followed these 3 commands exactly on Windows, Mac and Linux and it worked no problem
```
git clone https://github.com/DTLP/mini_tanks.git
cd mini_tanks
go run ./cmd/mini_tanks.go
```
Alternatively, if you're on Windows, you can try downloading `mini_tanks_v0.1.0_amd64.zip` and running the compiled .exe from the Releases [https://github.com/DTLP/mini_tanks/releases](https://github.com/DTLP/mini_tanks/releases)
